
// ── Capgemini-specific games ───────────────────────────────────
export const CAPGEMINI_GAMES = [
  {
    id: "deductive",
    title: "Deductive",
    desc: "Apply logical deduction to reach conclusions from a set of given premises and rules.",
    icon: "🔍",
    iconBg: "#eef2ff",
    iconColor: "#2563eb",
    difficulty: "Medium",
    diffColor: "#f59e0b",
    duration: "14 min",
    category: "Logical",
    questions: 20,
    tags: ["Capgemini"],
  },
  {
    id: "switch-challenge",
    title: "Switch Challenge",
    desc: "Rapidly switch between tasks and rule sets to test your cognitive flexibility.",
    icon: "🔀",
    iconBg: "#fdf2f8",
    iconColor: "#7c3aed",
    difficulty: "Hard",
    diffColor: "#ef4444",
    duration: "10 min",
    category: "Speed",
    questions: 25,
    tags: ["Capgemini"],
  },
  {
    id: "grid-challenge",
    title: "Grid Challenge",
    desc: "Solve spatial puzzles and identify patterns across dynamic grids of symbols and shapes.",
    icon: "⊞",
    iconBg: "#fff3eb",
    iconColor: "#f15a2b",
    difficulty: "Medium",
    diffColor: "#f59e0b",
    duration: "12 min",
    category: "Logical",
    questions: 18,
    tags: ["Capgemini"],
  },
  {
    id: "memory-bubble",
    title: "Memory Bubble",
    desc: "Watch bubbles light up in sequence, then tap them back in the exact same order — fast.",
    icon: "🧠",
    iconBg: "#eef2ff",
    iconColor: "#2563eb",
    difficulty: "Medium",
    diffColor: "#f59e0b",
    duration: "8 min",
    category: "Memory",
    questions: 20,
    tags: ["Capgemini"],
  },
  {
    id: "inductive-challenge",
    title: "Inductive Challenge",
    desc: "Identify rules from examples and generalise patterns to solve novel problems.",
    icon: "💡",
    iconBg: "#fffbeb",
    iconColor: "#f59e0b",
    difficulty: "Hard",
    diffColor: "#ef4444",
    duration: "15 min",
    category: "Logical",
    questions: 22,
    tags: ["Capgemini"],
  },
  {
    id: "motion-challenge",
    title: "Motion Challenge",
    desc: "Track moving objects, predict trajectories, and respond to visual motion cues under pressure.",
    icon: "🎯",
    iconBg: "#f0fdf4",
    iconColor: "#10b981",
    difficulty: "Hard",
    diffColor: "#ef4444",
    duration: "8 min",
    category: "Attention",
    questions: 30,
    tags: ["Capgemini"],
  },
];

export const GAMES = [
  {
    id: "pattern-matrix",
    title: "Pattern Matrix",
    desc: "Identify hidden patterns across a grid of symbols, shapes, and numbers.",
    icon: "◉",
    iconBg: "#fff3eb",
    iconColor: "#f15a2b",
    difficulty: "Medium",
    diffColor: "#f59e0b",
    duration: "12 min",
    category: "Logical",
    questions: 20,
    tags: ["TCS", "Infosys", "Wipro"],
  },
  {
    id: "memory-recall",
    title: "Memory Recall",
    desc: "Memorise sequences of numbers, words, or images and recall them accurately.",
    icon: "◈",
    iconBg: "#eef2ff",
    iconColor: "#2563eb",
    difficulty: "Easy",
    diffColor: "#10b981",
    duration: "8 min",
    category: "Memory",
    questions: 15,
    tags: ["Accenture", "Deloitte"],
  },
  {
    id: "reaction-time",
    title: "Reaction Time",
    desc: "Test your cognitive processing speed with rapid-fire visual and auditory cues.",
    icon: "◎",
    iconBg: "#fdf2f8",
    iconColor: "#7c3aed",
    difficulty: "Hard",
    diffColor: "#ef4444",
    duration: "6 min",
    category: "Speed",
    questions: 30,
    tags: ["Capgemini", "Cognizant"],
  },
  {
    id: "sequence-completion",
    title: "Sequence Completion",
    desc: "Complete number series, alphabetic sequences, and mixed pattern chains.",
    icon: "◆",
    iconBg: "#f0fdf4",
    iconColor: "#10b981",
    difficulty: "Medium",
    diffColor: "#f59e0b",
    duration: "15 min",
    category: "Quantitative",
    questions: 25,
    tags: ["TCS", "Capgemini", "Wipro"],
  },
  {
    id: "attention-focus",
    title: "Attention Focus",
    desc: "Spot differences, find anomalies, and track moving objects under distraction.",
    icon: "◐",
    iconBg: "#fffbeb",
    iconColor: "#f59e0b",
    difficulty: "Hard",
    diffColor: "#ef4444",
    duration: "10 min",
    category: "Attention",
    questions: 18,
    tags: ["Infosys", "Accenture", "TCS"],
  },
];
